//! Tests for the matchgen crate.
//!
//! This just includes `test-matchers.rs`, which is generated by `build.rs`. See
//! `tests/` and `benches/` for the actual test code.

// FIXME? We might want to add this to generated matchers. Alternatively, we
// could check if they could be made `const`.
#![allow(clippy::missing_const_for_fn)]

// Include generated code.
include!(concat!(env!("OUT_DIR"), "/test-matchers.rs"));
